CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS intermediate;
CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS dbo;


GRANT USAGE, CREATE ON SCHEMA raw TO project_user;
GRANT USAGE, CREATE ON SCHEMA staging TO project_user;
GRANT USAGE, CREATE ON SCHEMA intermediate TO project_user;
GRANT USAGE, CREATE ON SCHEMA mart TO project_user;
GRANT USAGE, CREATE ON SCHEMA reference TO project_user;
GRANT USAGE, CREATE ON SCHEMA dbo TO project_user;